DEEPSORT:
  MODEL_TYPE: ""
  MAX_DIST: 0.65 # The matching threshold. Samples with larger distance are considered an invalid match
  MAX_IOU_DISTANCE: 0.65 # Gating threshold. Associations with cost larger than this value are disregarded.
  MAX_AGE: 100 # Maximum number of missed misses before a track is deleted
  N_INIT: 10 # Number of frames that a track remains in initialization phase
  NN_BUDGET: 100 # Maximum size of the appearance descriptors gallery
  
